export enum CardType {
  Leaders = 'Leaders',
  Members = 'Members',
}

export enum CardFoil {
  Regular = 'Regular',
  Gold = 'Gold',
}

export enum CardRarity {
  Common = 'Common',
  Rare = 'Rare',
  Epic = 'Epic',
  Legendary = 'Legendary',
}

export enum CardFaction {
  Neutral = 'Neutral',
  Animal = 'Animal',
  Plant = 'Plant',
  Zombie = 'Zombie',
  Mech = 'Mech',
  Dragon = 'Dragon',
}

export type CardSkills =
  | null
  | string
  | {
      text: string;
      nums: number[][];
    };

export interface Card {
  id: number;
  image: string;
  name: string;
  nameEn: string;
  type: keyof typeof CardType;
  faction: keyof typeof CardFaction;
  rarity?: keyof typeof CardRarity;
  foil: keyof typeof CardFoil;
  cost: number;
  skills?: CardSkills;
  props?: [number, number?][];
}

export const cardsList: Card[] = [
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20039.png',
    id: 301,
    name: '狼牙棒',
    foil: 'Regular',
    cost: 2,
    nameEn: 'Spiked Bat',
    skills: null,
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10003.png',
    id: 307,
    name: '僵尸宝贝',
    foil: 'Regular',
    cost: 0,
    nameEn: 'Zombie Baby',
    type: 'Leaders',
    skills: {
      text: '开战时>己方所有成员增加{{0}}战斗力',
      nums: [[1], [1], [1], [1], [2], [2], [2], [2], [2], [2]],
    },
    faction: 'Zombie',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20003.png',
    id: 310,
    name: '死亡骑士',
    foil: 'Regular',
    cost: 4,
    skills: null,
    nameEn: 'Death Knight',
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20030_g.png',
    id: 311,
    name: '僵尸王子',
    foil: 'Gold',
    cost: 3,
    nameEn: 'Prince Zombie',
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20033_g.png',
    id: 315,
    name: '友善母鸡',
    foil: 'Gold',
    cost: 2,
    skills: null,
    nameEn: 'Friendly Hen',
    type: 'Members',
    faction: 'Animal',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20032_g.png',
    id: 317,
    name: '拳击手套',
    foil: 'Gold',
    cost: 1,
    skills: null,
    nameEn: 'Boxing Gloves',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10001.png',
    id: 318,
    name: '疯狂兔子',
    foil: 'Regular',
    cost: 0,
    nameEn: 'Mad Rabbit',
    type: 'Leaders',
    faction: 'Animal',
    rarity: 'Common',
    skills: {
      text: '开战时>己方所有成员增加{{0}}战斗力',
      nums: [[1], [1], [1], [1], [2], [2], [2], [2], [2], [2]],
    },
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20042_g.png',
    id: 319,
    name: '散弹枪',
    foil: 'Gold',
    cost: 5,
    skills: null,
    nameEn: 'Shotgun',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20006.png',
    id: 320,
    name: '弹药箱',
    foil: 'Regular',
    cost: 2,
    nameEn: 'Ammo Crate',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20029_g.png',
    id: 322,
    name: '蜗牛',
    foil: 'Gold',
    cost: 1,
    nameEn: 'Snail',
    skills: null,
    type: 'Members',
    faction: 'Animal',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20030.png',
    id: 323,
    name: '僵尸王子',
    foil: 'Regular',
    cost: 3,
    nameEn: 'Prince Zombie',
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20023.png',
    id: 324,
    name: '狮子王',
    foil: 'Regular',
    cost: 7,
    skills: {
      text: '攻击前>自身增加{{0}}战斗力',
      nums: [[4], [4], [5], [5], [6], [6], [6], [7], [7], [9]],
    },
    nameEn: 'Lion King',
    type: 'Members',
    faction: 'Animal',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20038_g.png',
    id: 325,
    name: '水手僵尸',
    foil: 'Gold',
    cost: 1,
    nameEn: 'Sailor Zombie',
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20017.png',
    id: 326,
    name: '南瓜',
    foil: 'Regular',
    cost: 4,
    nameEn: 'Pumpkin',
    type: 'Members',
    faction: 'Plant',
    rarity: 'Legendary',
    skills: {
      text: '受伤后>己方所有植物成员增加{{0}}护甲',
      nums: [[1], [1], [2], [2], [3], [3], [3], [3], [3], [3]],
    },
    props: [
      [6, 10],
      [7, 11],
      [8, 12],
      [9, 13],
      [10, 14],
      [11, 15],
      [12, 16],
      [13, 17],
      [14, 18],
      [15, 27],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20058.png',
    id: 328,
    name: '红菜头',
    foil: 'Regular',
    cost: 3,
    nameEn: 'Radish',
    type: 'Members',
    faction: 'Plant',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20023_g.png',
    id: 330,
    foil: 'Gold',
    cost: 7,
    nameEn: 'Lion King',
    name: '狮子王',
    skills: {
      text: '攻击前>自身增加{{0}}战斗力',
      nums: [[4], [4], [5], [5], [6], [6], [6], [7], [7], [9]],
    },
    type: 'Members',
    faction: 'Animal',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20031_g.png',
    id: 331,
    name: '扫把',
    foil: 'Gold',
    cost: 3,
    skills: null,
    nameEn: 'Broom',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10006.png',
    id: 332,
    name: '啦啦队长僵尸',
    foil: 'Regular',
    cost: 0,
    nameEn: 'Cheerleader Zombie',
    type: 'Leaders',
    skills: {
      text: '己方僵尸成员被击败时>敌方1个成员受到{{0}}伤害，只能触发4次',
      nums: [[3], [3], [4], [4], [5], [5], [5], [7], [7], [7]],
    },
    faction: 'Zombie',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20066_g.png',
    id: 333,
    name: '番茄先生',
    foil: 'Gold',
    cost: 3,
    nameEn: 'Mr. Tomato',
    type: 'Members',
    faction: 'Plant',
    rarity: 'Epic',
    skills: '受伤后>后方最近1位成员受到1伤害',
    props: [
      [7, 4],
      [8, 4],
      [9, 4],
      [10, 4],
      [11, 4],
      [12, 4],
      [13, 4],
      [14, 4],
      [15, 4],
      [17, 4],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20012.png',
    id: 334,
    name: '小丑僵尸',
    foil: 'Regular',
    cost: 4,
    nameEn: 'Clown Zombie',
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10001_g.png',
    id: 335,
    foil: 'Gold',
    nameEn: 'Mad Rabbit',
    name: '疯狂兔子',
    cost: 0,
    type: 'Leaders',
    faction: 'Animal',
    rarity: 'Common',
    skills: {
      text: '开战时>己方所有成员增加{{0}}战斗力',
      nums: [[1], [1], [1], [1], [2], [2], [2], [2], [2], [2]],
    },
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20065_g.png',
    id: 336,
    name: '反弹盾',
    foil: 'Gold',
    cost: 4,
    nameEn: 'Raging Shield',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20052.png',
    id: 337,
    name: 'UFO',
    foil: 'Regular',
    cost: 7,
    nameEn: 'UFO',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20028_g.png',
    id: 338,
    name: '炸弹僵尸',
    foil: 'Gold',
    cost: 4,
    nameEn: 'Bomb Zombie',
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20002.png',
    id: 339,
    name: '海岛僵尸',
    foil: 'Regular',
    cost: 5,
    nameEn: 'Pirate Zombie',
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20017_g.png',
    id: 341,
    name: '南瓜',
    foil: 'Gold',
    cost: 4,
    nameEn: 'Pumpkin',
    type: 'Members',
    faction: 'Plant',
    rarity: 'Legendary',
    skills: {
      text: '受伤后>己方所有植物成员增加{{0}}护甲',
      nums: [[1], [1], [2], [2], [3], [3], [3], [3], [3], [3]],
    },
    props: [
      [6, 10],
      [7, 11],
      [8, 12],
      [9, 13],
      [10, 14],
      [11, 15],
      [12, 16],
      [13, 17],
      [14, 18],
      [15, 27],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20055.png',
    id: 342,
    name: '大炮',
    foil: 'Regular',
    cost: 7,
    skills: null,
    nameEn: 'Cannon',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20052_g.png',
    id: 343,
    name: 'UFO',
    foil: 'Gold',
    cost: 7,
    nameEn: 'UFO',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20055_g.png',
    id: 344,
    name: '大炮',
    foil: 'Gold',
    cost: 7,
    skills: null,
    nameEn: 'Cannon',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20057.png',
    id: 345,
    name: '电锯',
    foil: 'Regular',
    cost: 6,
    skills: null,
    nameEn: 'Chainsaw',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20004.png',
    id: 346,
    name: '铁头盔',
    foil: 'Regular',
    cost: 6,
    nameEn: 'Iron Helmet',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20004_g.png',
    id: 347,
    foil: 'Gold',
    nameEn: 'Iron Helmet',
    name: '铁头盔',
    cost: 6,
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20059.png',
    id: 348,
    name: '仙人掌',
    foil: 'Regular',
    cost: 5,
    nameEn: 'Cactus',
    type: 'Members',
    faction: 'Plant',
    rarity: 'Rare',
    skills: {
      text: '受伤后>敌方队头成员受到随机{{0}}到{{1}}伤害',
      nums: [
        [2, 4],
        [2, 4],
        [3, 5],
        [3, 5],
        [4, 6],
        [4, 6],
        [4, 6],
        [5, 7],
        [5, 7],
        [6, 8],
      ],
    },
    props: [
      [4, 8],
      [5, 9],
      [6, 10],
      [7, 11],
      [8, 12],
      [9, 13],
      [10, 14],
      [11, 15],
      [12, 16],
      [13, 17],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20057_g.png',
    id: 349,
    foil: 'Gold',
    nameEn: 'Chainsaw',
    name: '电锯',
    cost: 6,
    skills: null,
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20021.png',
    id: 350,
    name: '乌龟大哥',
    foil: 'Regular',
    nameEn: 'Tortoise Bro',
    cost: 5,
    type: 'Members',
    faction: 'Animal',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20059_g.png',
    id: 351,
    foil: 'Gold',
    nameEn: 'Cactus',
    name: '仙人掌',
    cost: 5,
    type: 'Members',
    faction: 'Plant',
    rarity: 'Rare',
    skills: {
      text: '受伤后>敌方队头成员受到随机{{0}}到{{1}}伤害',
      nums: [
        [2, 4],
        [2, 4],
        [3, 5],
        [3, 5],
        [4, 6],
        [4, 6],
        [4, 6],
        [5, 7],
        [5, 7],
        [6, 8],
      ],
    },
    props: [
      [4, 8],
      [5, 9],
      [6, 10],
      [7, 11],
      [8, 12],
      [9, 13],
      [10, 14],
      [11, 15],
      [12, 16],
      [13, 17],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20018.png',
    id: 352,
    name: '舞王僵尸',
    foil: 'Regular',
    cost: 5,
    nameEn: 'Dancer Zombie',
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20042.png',
    id: 353,
    name: '散弹枪',
    foil: 'Regular',
    cost: 5,
    skills: null,
    nameEn: 'Shotgun',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20018_g.png',
    id: 354,
    foil: 'Gold',
    nameEn: 'Dancer Zombie',
    cost: 5,
    name: '舞王僵尸',
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20067.png',
    id: 355,
    name: '凤梨',
    foil: 'Regular',
    nameEn: 'Pineapple',
    cost: 4,
    type: 'Members',
    faction: 'Plant',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20065.png',
    id: 356,
    name: '反弹盾',
    foil: 'Regular',
    cost: 4,
    nameEn: 'Raging Shield',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20067_g.png',
    id: 357,
    foil: 'Gold',
    nameEn: 'Pineapple',
    cost: 4,
    name: '凤梨',
    type: 'Members',
    faction: 'Plant',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20063.png',
    id: 358,
    name: '红辣椒',
    cost: 4,
    foil: 'Regular',
    nameEn: 'Red Chili',
    type: 'Members',
    faction: 'Plant',
    rarity: 'Rare',
    skills: {
      text: '前方最近成员受伤后>自身增加{{0}}点战斗力',
      nums: [[2], [2], [3], [3], [4], [4], [4], [5], [5], [5]],
    },
    props: [[7], [8], [9], [10], [11], [12], [13], [14], [15], [18]],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20047.png',
    id: 359,
    name: '号角',
    cost: 4,
    foil: 'Regular',
    nameEn: 'Trumpet',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20063_g.png',
    id: 360,
    foil: 'Gold',
    nameEn: 'Red Chili',
    name: '红辣椒',
    cost: 4,
    type: 'Members',
    faction: 'Plant',
    rarity: 'Rare',
    skills: {
      text: '前方最近成员受伤后>自身增加{{0}}点战斗力',
      nums: [[2], [2], [3], [3], [4], [4], [4], [5], [5], [5]],
    },
    props: [[7], [8], [9], [10], [11], [12], [13], [14], [15], [18]],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20028.png',
    id: 361,
    foil: 'Regular',
    nameEn: 'Bomb Zombie',
    cost: 4,
    name: '炸弹僵尸',
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20047_g.png',
    id: 362,
    foil: 'Gold',
    nameEn: 'Trumpet',
    cost: 4,
    name: '号角',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20022.png',
    id: 363,
    name: '路障僵尸',
    foil: 'Regular',
    cost: 4,
    nameEn: 'Roadblock Zombie',
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20014.png',
    id: 364,
    name: '锅铲',
    cost: 4,
    foil: 'Regular',
    nameEn: 'Turner',
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20022_g.png',
    id: 365,
    foil: 'Gold',
    nameEn: 'Roadblock Zombie',
    cost: 4,
    name: '路障僵尸',
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20009.png',
    id: 366,
    name: '快乐绵羊',
    foil: 'Regular',
    cost: 4,
    nameEn: 'Joyful Lamb',
    type: 'Members',
    faction: 'Animal',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20009_g.png',
    id: 367,
    foil: 'Gold',
    cost: 4,
    nameEn: 'Joyful Lamb',
    name: '快乐绵羊',
    type: 'Members',
    faction: 'Animal',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20014_g.png',
    id: 368,
    foil: 'Gold',
    nameEn: 'Turner',
    name: '锅铲',
    cost: 4,
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20056.png',
    id: 369,
    name: '斧头',
    foil: 'Regular',
    nameEn: 'Axe',
    type: 'Members',
    cost: 4,
    skills: null,
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20007.png',
    id: 370,
    name: '骄傲野猪',
    foil: 'Regular',
    cost: 4,
    nameEn: 'Arrogant Boar',
    type: 'Members',
    faction: 'Animal',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20056_g.png',
    id: 371,
    foil: 'Gold',
    nameEn: 'Axe',
    name: '斧头',
    cost: 4,
    skills: null,
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20007_g.png',
    id: 372,
    foil: 'Gold',
    nameEn: 'Arrogant Boar',
    name: '骄傲野猪',
    type: 'Members',
    cost: 4,
    faction: 'Animal',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20062.png',
    id: 373,
    name: '酪梨',
    foil: 'Regular',
    nameEn: 'Avocado',
    cost: 5,
    type: 'Members',
    faction: 'Plant',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20003_g.png',
    id: 374,
    foil: 'Gold',
    nameEn: 'Death Knight',
    name: '死亡骑士',
    cost: 4,
    skills: null,
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20060.png',
    id: 375,
    name: '勇敢海狸',
    foil: 'Regular',
    nameEn: 'Brave Beaver',
    cost: 3,
    skills: null,
    type: 'Members',
    faction: 'Animal',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10013.png',
    id: 376,
    name: '麋鹿大叔',
    foil: 'Regular',
    nameEn: 'Uncle Elk',
    type: 'Leaders',
    cost: 0,
    faction: 'Animal',
    rarity: 'Rare',
    skills: {
      text: '己方动物成员破敌并存活时>增加{{0}}战斗力，只能触发4次',
      nums: [[2], [2], [3], [3], [4], [4], [4], [5], [5], [5]],
    },
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20040.png',
    id: 377,
    name: '农夫僵尸',
    foil: 'Regular',
    nameEn: 'Farmer Zombie',
    cost: 3,
    skills: null,
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20016.png',
    id: 378,
    name: '超能僵尸',
    foil: 'Regular',
    nameEn: 'Super Zombie',
    cost: 7,
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20019.png',
    id: 379,
    name: '贪婪鲨鱼',
    foil: 'Regular',
    nameEn: 'Greedy Shark',
    type: 'Members',
    cost: 3,
    faction: 'Animal',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20026.png',
    id: 380,
    name: '狡猾狐狸',
    foil: 'Regular',
    nameEn: 'Cunning Fox',
    type: 'Members',
    cost: 4,
    faction: 'Animal',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10015.png',
    id: 381,
    name: '僵尸新娘',
    foil: 'Regular',
    nameEn: 'Zombie Bride',
    type: 'Leaders',
    skills: {
      text: '己方召唤僵尸成员时>己方战斗力最高的僵尸成员增加随机{{0}}到{{1}}战斗力，只能触发4次',
      nums: [
        [2, 3],
        [2, 3],
        [3, 4],
        [3, 4],
        [4, 5],
        [4, 5],
        [4, 5],
        [5, 6],
        [5, 6],
        [5, 6],
      ],
    },
    cost: 2,
    faction: 'Zombie',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20064.png',
    id: 382,
    name: '卷心菜',
    foil: 'Regular',
    nameEn: 'Cabbage',
    type: 'Members',
    cost: 7,
    faction: 'Plant',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20060_g.png',
    id: 383,
    foil: 'Gold',
    nameEn: 'Brave Beaver',
    name: '勇敢海狸',
    type: 'Members',
    cost: 3,
    skills: null,
    faction: 'Animal',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20044.png',
    id: 384,
    name: '矿工僵尸',
    foil: 'Regular',
    nameEn: 'Miner Zombie',
    cost: 3,
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20050.png',
    id: 385,
    name: '充气锤',
    foil: 'Regular',
    nameEn: 'Inflatable Hammer',
    cost: 1,
    skills: null,
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20058_g.png',
    id: 386,
    foil: 'Gold',
    nameEn: 'Radish',
    name: '红菜头',
    type: 'Members',
    cost: 3,
    faction: 'Plant',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20019_g.png',
    id: 387,
    foil: 'Gold',
    nameEn: 'Greedy Shark',
    name: '贪婪鲨鱼',
    type: 'Members',
    cost: 3,
    faction: 'Animal',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20044_g.png',
    id: 388,
    foil: 'Gold',
    nameEn: 'Miner Zombie',
    name: '矿工僵尸',
    type: 'Members',
    cost: 3,
    faction: 'Zombie',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20040_g.png',
    id: 389,
    foil: 'Gold',
    nameEn: 'Farmer Zombie',
    name: '农夫僵尸',
    type: 'Members',
    cost: 3,
    skills: null,
    faction: 'Zombie',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20031.png',
    id: 390,
    foil: 'Regular',
    nameEn: 'Broom',
    name: '扫把',
    type: 'Members',
    cost: 3,
    skills: null,
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20035.png',
    id: 391,
    name: '龙虾',
    foil: 'Regular',
    nameEn: 'Lobster',
    type: 'Members',
    cost: 2,
    skills: null,
    faction: 'Animal',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20061.png',
    id: 392,
    name: '毒蘑菇',
    foil: 'Regular',
    nameEn: 'Poison Mushroom',
    type: 'Members',
    cost: 1,
    skills: null,
    faction: 'Plant',
    rarity: 'Common',
    props: [
      [3, 0],
      [3, 1],
      [3, 2],
      [3, 3],
      [3, 4],
      [3, 5],
      [3, 6],
      [3, 7],
      [3, 8],
      [3, 9],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20034.png',
    id: 393,
    name: '苹果',
    foil: 'Regular',
    nameEn: 'Apple',
    type: 'Members',
    cost: 2,
    skills: null,
    faction: 'Plant',
    rarity: 'Common',
    props: [
      [5, 0],
      [5, 1],
      [5, 2],
      [5, 3],
      [5, 4],
      [5, 5],
      [5, 6],
      [5, 7],
      [5, 8],
      [5, 15],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20041.png',
    id: 394,
    name: '硬坚果',
    foil: 'Regular',
    nameEn: 'Hardshell Nut',
    type: 'Members',
    cost: 3,
    skills: null,
    faction: 'Plant',
    rarity: 'Common',
    props: [
      [3, 8],
      [4, 8],
      [5, 8],
      [6, 8],
      [7, 8],
      [8, 8],
      [9, 8],
      [10, 8],
      [11, 8],
      [13, 8],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10002_g.png',
    id: 395,
    name: '玉米先生',
    foil: 'Gold',
    nameEn: 'Mr. Corn',
    type: 'Leaders',
    skills: {
      text: '开战时>己方所有成员增加{{0}}战斗力',
      nums: [[1], [1], [1], [1], [2], [2], [2], [2], [2], [2]],
    },
    cost: 0,
    faction: 'Plant',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10004_g.png',
    id: 396,
    name: '猛虎',
    foil: 'Gold',
    nameEn: 'Furious Tiger',
    type: 'Leaders',
    skills: {
      text: '己方动物成员攻击前>该成员增加{{0}}战斗力，只能触发4次',
      nums: [[4], [4], [5], [5], [6], [6], [6], [7], [7], [9]],
    },
    cost: 2,
    faction: 'Animal',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20035_g.png',
    id: 397,
    foil: 'Gold',
    nameEn: 'Lobster',
    name: '龙虾',
    type: 'Members',
    cost: 2,
    skills: null,
    faction: 'Animal',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20013.png',
    id: 398,
    name: '平底锅',
    foil: 'Regular',
    nameEn: 'Frying Pan',
    type: 'Members',
    cost: 2,
    skills: null,
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20013_g.png',
    id: 399,
    foil: 'Gold',
    nameEn: 'Frying Pan',
    name: '平底锅',
    type: 'Members',
    cost: 2,
    skills: null,
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20039_g.png',
    id: 400,
    foil: 'Gold',
    nameEn: 'Spiked Bat',
    name: '狼牙棒',
    type: 'Members',
    cost: 2,
    skills: null,
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20033.png',
    id: 401,
    foil: 'Regular',
    nameEn: 'Friendly Hen',
    name: '友善母鸡',
    cost: 2,
    skills: null,
    type: 'Members',
    faction: 'Animal',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20034_g.png',
    id: 402,
    foil: 'Gold',
    nameEn: 'Apple',
    name: '苹果',
    cost: 2,
    skills: null,
    type: 'Members',
    faction: 'Plant',
    rarity: 'Common',
    props: [
      [5, 0],
      [5, 1],
      [5, 2],
      [5, 3],
      [5, 4],
      [5, 5],
      [5, 6],
      [5, 7],
      [5, 8],
      [5, 15],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20050_g.png',
    id: 403,
    foil: 'Gold',
    nameEn: 'Inflatable Hammer',
    name: '充气锤',
    cost: 1,
    skills: null,
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10014.png',
    id: 404,
    name: '青花菜爷爷',
    foil: 'Regular',
    cost: 2,
    nameEn: 'Grandpa Broccoli',
    type: 'Leaders',
    skills: {
      text: '己方植物成员受伤时>增加{{0}}护甲，只能触发4次',
      nums: [[6], [6], [8], [8], [10], [10], [10], [12], [12], [15]],
    },
    faction: 'Plant',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20038.png',
    id: 405,
    foil: 'Regular',
    nameEn: 'Sailor Zombie',
    name: '水手僵尸',
    cost: 1,
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20061_g.png',
    id: 406,
    foil: 'Gold',
    nameEn: 'Poison Mushroom',
    name: '毒蘑菇',
    cost: 1,
    skills: null,
    type: 'Members',
    faction: 'Plant',
    rarity: 'Common',
    props: [
      [3, 0],
      [3, 1],
      [3, 2],
      [3, 3],
      [3, 4],
      [3, 5],
      [3, 6],
      [3, 7],
      [3, 8],
      [3, 9],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20029.png',
    id: 407,
    foil: 'Regular',
    nameEn: 'Snail',
    name: '蜗牛',
    cost: 1,
    skills: null,
    type: 'Members',
    faction: 'Animal',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10013_g.png',
    id: 408,
    foil: 'Gold',
    nameEn: 'Uncle Elk',
    name: '麋鹿大叔',
    cost: 0,
    type: 'Leaders',
    faction: 'Animal',
    rarity: 'Rare',
    skills: {
      text: '己方动物成员破敌并存活时>增加{{0}}战斗力，只能触发4次',
      nums: [[2], [2], [3], [3], [4], [4], [4], [5], [5], [5]],
    },
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10005.png',
    id: 409,
    name: '椰子',
    foil: 'Regular',
    nameEn: 'Coconut',
    cost: 0,
    type: 'Leaders',
    skills: {
      text: '己方植物成员攻击前>该成员增加{{0}}护甲，只能触发4次',
      nums: [[3], [3], [4], [4], [5], [5], [5], [8], [8], [8]],
    },
    faction: 'Plant',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10006_g.png',
    id: 410,
    foil: 'Gold',
    nameEn: 'Cheerleader Zombie',
    name: '啦啦队长僵尸',
    skills: {
      text: '己方僵尸成员被击败时>敌方1个成员受到{{0}}伤害，只能触发4次',
      nums: [[3], [3], [4], [4], [5], [5], [5], [7], [7], [7]],
    },
    cost: 0,
    type: 'Leaders',
    faction: 'Zombie',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10005_g.png',
    id: 411,
    foil: 'Gold',
    nameEn: 'Coconut',
    name: '椰子',
    cost: 0,
    skills: {
      text: '己方植物成员攻击前>该成员增加{{0}}护甲，只能触发4次',
      nums: [[3], [3], [4], [4], [5], [5], [5], [8], [8], [8]],
    },
    type: 'Leaders',
    faction: 'Plant',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10003_g.png',
    id: 412,
    foil: 'Gold',
    nameEn: 'Zombie Baby',
    name: '僵尸宝贝',
    type: 'Leaders',
    cost: 0,
    skills: {
      text: '开战时>己方所有成员增加{{0}}战斗力',
      nums: [[1], [1], [1], [1], [2], [2], [2], [2], [2], [2]],
    },
    faction: 'Zombie',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10002.png',
    id: 413,
    foil: 'Regular',
    nameEn: 'Mr. Corn',
    name: '玉米先生',
    type: 'Leaders',
    skills: {
      text: '开战时>己方所有成员增加{{0}}战斗力',
      nums: [[1], [1], [1], [1], [2], [2], [2], [2], [2], [2]],
    },
    cost: 0,
    faction: 'Plant',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20008.png',
    id: 414,
    name: '火箭',
    foil: 'Regular',
    nameEn: 'Rocket',
    cost: 5,
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20010.png',
    id: 415,
    name: '愤怒公牛',
    foil: 'Regular',
    nameEn: 'Angry Bull',
    type: 'Members',
    cost: 6,
    faction: 'Animal',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20027.png',
    id: 416,
    name: '蛇',
    foil: 'Regular',
    nameEn: 'Snake',
    type: 'Members',
    cost: 5,
    faction: 'Animal',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20008_g.png',
    id: 417,
    foil: 'Gold',
    nameEn: 'Rocket',
    name: '火箭',
    type: 'Members',
    cost: 5,
    faction: 'Neutral',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20066.png',
    id: 418,
    foil: 'Regular',
    nameEn: 'Mr. Tomato',
    name: '番茄先生',
    type: 'Members',
    cost: 3,
    faction: 'Plant',
    rarity: 'Epic',
    skills: '受伤后>后方最近1位成员受到1伤害',
    props: [
      [7, 4],
      [8, 4],
      [9, 4],
      [10, 4],
      [11, 4],
      [12, 4],
      [13, 4],
      [14, 4],
      [15, 4],
      [17, 4],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10004.png',
    id: 419,
    foil: 'Regular',
    nameEn: 'Furious Tiger',
    name: '猛虎',
    type: 'Leaders',
    cost: 2,
    skills: {
      text: '己方动物成员攻击前>该成员增加{{0}}战斗力，只能触发4次',
      nums: [[4], [4], [5], [5], [6], [6], [6], [7], [7], [9]],
    },
    faction: 'Animal',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20015.png',
    id: 420,
    name: '饥饿宝箱怪',
    foil: 'Regular',
    nameEn: 'Starving Mimic',
    type: 'Members',
    cost: 5,
    faction: 'Neutral',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20005.png',
    id: 421,
    name: '球星僵尸',
    foil: 'Regular',
    nameEn: 'Star Zombie',
    type: 'Members',
    cost: 6,
    faction: 'Zombie',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20025.png',
    id: 422,
    name: '毒药',
    foil: 'Regular',
    nameEn: 'Poison',
    cost: 3,
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Epic',
    skills: '攻击造成伤害时>破坏攻击目标',
    props: [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20036.png',
    id: 423,
    name: '派对僵尸',
    foil: 'Regular',
    nameEn: 'Party Zombie',
    type: 'Members',
    cost: 2,
    faction: 'Zombie',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20011.png',
    id: 424,
    foil: 'Regular',
    nameEn: 'Master Panda',
    name: '熊猫大师',
    type: 'Members',
    cost: 7,
    faction: 'Animal',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20041_g.png',
    id: 425,
    foil: 'Gold',
    nameEn: 'Hardshell Nut',
    name: '硬坚果',
    cost: 3,
    skills: null,
    type: 'Members',
    faction: 'Plant',
    rarity: 'Common',
    props: [
      [3, 8],
      [4, 8],
      [5, 8],
      [6, 8],
      [7, 8],
      [8, 8],
      [9, 8],
      [10, 8],
      [11, 8],
      [13, 8],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20020.png',
    id: 426,
    name: '西瓜',
    foil: 'Regular',
    nameEn: 'Watermelon',
    type: 'Members',
    cost: 6,
    faction: 'Plant',
    rarity: 'Epic',
    skills: {
      text: '受伤后>后方最近1个成员增加{{0}}战斗力与{{1}}护甲',
      nums: [
        [2, 2],
        [2, 2],
        [3, 2],
        [3, 2],
        [3, 4],
        [3, 4],
        [3, 4],
        [4, 4],
        [4, 4],
        [4, 4],
      ],
    },
    props: [
      [11, 1],
      [12, 2],
      [13, 3],
      [14, 4],
      [15, 5],
      [16, 6],
      [17, 7],
      [18, 8],
      [19, 9],
      [23, 10],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20032.png',
    id: 427,
    name: '拳击手套',
    foil: 'Regular',
    nameEn: 'Boxing Gloves',
    cost: 1,
    skills: null,
    type: 'Members',
    faction: 'Neutral',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20015_g.png',
    id: 428,
    foil: 'Gold',
    nameEn: 'Starving Mimic',
    name: '饥饿宝箱怪',
    type: 'Members',
    cost: 5,
    faction: 'Neutral',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10014_g.png',
    id: 429,
    foil: 'Gold',
    nameEn: 'Grandpa Broccoli',
    name: '青花菜爷爷',
    cost: 2,
    skills: {
      text: '己方植物成员受伤时>增加{{0}}护甲，只能触发4次',
      nums: [[6], [6], [8], [8], [10], [10], [10], [12], [12], [15]],
    },
    type: 'Leaders',
    faction: 'Plant',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10015_g.png',
    id: 430,
    foil: 'Gold',
    nameEn: 'Zombie Bride',
    name: '僵尸新娘',
    skills: {
      text: '己方召唤僵尸成员时>己方战斗力最高的僵尸成员增加随机{{0}}到{{1}}战斗力，只能触发4次',
      nums: [
        [2, 3],
        [2, 3],
        [3, 4],
        [3, 4],
        [4, 5],
        [4, 5],
        [4, 5],
        [5, 6],
        [5, 6],
        [5, 6],
      ],
    },
    type: 'Leaders',
    cost: 2,
    faction: 'Zombie',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20016_g.png',
    id: 431,
    foil: 'Gold',
    nameEn: 'Super Zombie',
    name: '超能僵尸',
    cost: 7,
    type: 'Members',
    faction: 'Zombie',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20011_g.png',
    id: 432,
    name: '熊猫大师',
    foil: 'Gold',
    nameEn: 'Master Panda',
    cost: 7,
    type: 'Members',
    faction: 'Animal',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20020_g.png',
    id: 433,
    foil: 'Gold',
    nameEn: 'Watermelon',
    name: '西瓜',
    cost: 6,
    type: 'Members',
    faction: 'Plant',
    rarity: 'Epic',
    skills: {
      text: '受伤后>后方最近1个成员增加{{0}}战斗力与{{1}}护甲',
      nums: [
        [2, 2],
        [2, 2],
        [3, 2],
        [3, 2],
        [3, 4],
        [3, 4],
        [3, 4],
        [4, 4],
        [4, 4],
        [4, 4],
      ],
    },
    props: [
      [11, 1],
      [12, 2],
      [13, 3],
      [14, 4],
      [15, 5],
      [16, 6],
      [17, 7],
      [18, 8],
      [19, 9],
      [23, 10],
    ],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20027_g.png',
    id: 434,
    foil: 'Gold',
    nameEn: 'Snake',
    name: '蛇',
    type: 'Members',
    cost: 5,
    faction: 'Animal',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20068_g.png',
    id: 435,
    name: '大蒜',
    foil: 'Gold',
    nameEn: 'Garlic',
    skills: {
      text: '受到攻击后并存活>后方最近1个成员受到1伤害，该成员增加{{0}}战斗力',
      nums: [[3], [3], [4], [4], [5], [5], [5], [6], [6], [7]],
    },
    type: 'Members',
    cost: 7,
    faction: 'Plant',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20062_g.png',
    id: 436,
    foil: 'Gold',
    nameEn: 'Avocado',
    name: '酪梨',
    type: 'Members',
    cost: 5,
    faction: 'Plant',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20006_g.png',
    id: 437,
    foil: 'Gold',
    nameEn: 'Ammo Crate',
    name: '弹药箱',
    type: 'Members',
    cost: 2,
    faction: 'Neutral',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20005_g.png',
    id: 438,
    foil: 'Gold',
    nameEn: 'Star Zombie',
    name: '球星僵尸',
    type: 'Members',
    cost: 6,
    faction: 'Zombie',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20012_g.png',
    id: 439,
    foil: 'Gold',
    nameEn: 'Clown Zombie',
    name: '小丑僵尸',
    type: 'Members',
    cost: 4,
    faction: 'Zombie',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20010_g.png',
    id: 440,
    foil: 'Gold',
    nameEn: 'Angry Bull',
    name: '愤怒公牛',
    type: 'Members',
    cost: 6,
    faction: 'Animal',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20068.png',
    id: 441,
    foil: 'Regular',
    nameEn: 'Garlic',
    name: '大蒜',
    skills: {
      text: '受到攻击后并存活>后方最近1个成员受到1伤害，该成员增加{{0}}战斗力',
      nums: [[3], [3], [4], [4], [5], [5], [5], [6], [6], [7]],
    },
    type: 'Members',
    cost: 7,
    faction: 'Plant',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20064_g.png',
    id: 442,
    foil: 'Gold',
    nameEn: 'Cabbage',
    name: '卷心菜',
    type: 'Members',
    cost: 7,
    faction: 'Plant',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20037.png',
    id: 443,
    name: '榴莲特务',
    foil: 'Regular',
    nameEn: 'Durian Agent',
    type: 'Members',
    cost: 3,
    faction: 'Plant',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20021_g.png',
    id: 445,
    foil: 'Gold',
    nameEn: 'Tortoise Bro',
    name: '乌龟大哥',
    type: 'Members',
    cost: 5,
    faction: 'Animal',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20036_g.png',
    id: 446,
    foil: 'Gold',
    nameEn: 'Party Zombie',
    name: '派对僵尸',
    type: 'Members',
    cost: 2,
    faction: 'Zombie',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20025_g.png',
    id: 447,
    foil: 'Gold',
    nameEn: 'Poison',
    name: '毒药',
    type: 'Members',
    cost: 3,
    faction: 'Neutral',
    rarity: 'Epic',
    skills: '攻击造成伤害时>破坏攻击目标',
    props: [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]],
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20002_g.png',
    id: 448,
    foil: 'Gold',
    nameEn: 'Pirate Zombie',
    name: '海岛僵尸',
    type: 'Members',
    cost: 5,
    faction: 'Zombie',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20026_g.png',
    id: 449,
    foil: 'Gold',
    nameEn: 'Cunning Fox',
    name: '狡猾狐狸',
    type: 'Members',
    cost: 4,
    faction: 'Animal',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20043.png',
    id: 450,
    name: '警用防爆盾',
    foil: 'Regular',
    nameEn: 'Riot Shield',
    type: 'Members',
    cost: 3,
    faction: 'Neutral',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20024.png',
    id: 451,
    name: '青蛙',
    foil: 'Regular',
    nameEn: 'Frog',
    type: 'Members',
    cost: 4,
    faction: 'Animal',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20046_g.png',
    id: 452,
    name: '疯博士僵尸',
    foil: 'Gold',
    nameEn: 'Crazy Doctor Zombie',
    type: 'Members',
    cost: 7,
    faction: 'Zombie',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20069.png',
    id: 453,
    name: '榴莲将军',
    foil: 'Regular',
    nameEn: 'Durian Commander',
    type: 'Members',
    cost: 6,
    faction: 'Plant',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20048.png',
    id: 454,
    name: '狼王',
    foil: 'Regular',
    nameEn: 'Wolf King',
    skills: {
      text: '攻击后并存活>己方所有动物成员增加{{0}}战斗力',
      nums: [[1], [1], [2], [2], [3], [3], [3], [3], [3], [3]],
    },
    type: 'Members',
    cost: 5,
    faction: 'Animal',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20053.png',
    id: 455,
    name: '水桶僵尸',
    foil: 'Regular',
    nameEn: 'Barrel Zombie',
    type: 'Members',
    cost: 5,
    faction: 'Zombie',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20043_g.png',
    id: 457,
    foil: 'Gold',
    nameEn: 'Riot Shield',
    name: '警用防爆盾',
    type: 'Members',
    cost: 3,
    faction: 'Neutral',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20037_g.png',
    id: 458,
    foil: 'Gold',
    nameEn: 'Durian Agent',
    name: '榴莲特务',
    type: 'Members',
    cost: 3,
    faction: 'Plant',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20046.png',
    id: 459,
    foil: 'Regular',
    nameEn: 'Crazy Doctor Zombie',
    name: '疯博士僵尸',
    type: 'Members',
    cost: 7,
    faction: 'Zombie',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20053_g.png',
    id: 460,
    foil: 'Gold',
    nameEn: 'Barrel Zombie',
    name: '水桶僵尸',
    type: 'Members',
    cost: 5,
    faction: 'Zombie',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20024_g.png',
    id: 461,
    foil: 'Gold',
    nameEn: 'Frog',
    name: '青蛙',
    type: 'Members',
    cost: 4,
    faction: 'Animal',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20048_g.png',
    id: 462,
    name: '狼王',
    foil: 'Gold',
    skills: {
      text: '攻击后并存活>己方所有动物成员增加{{0}}战斗力',
      nums: [[1], [1], [2], [2], [3], [3], [3], [3], [3], [3]],
    },
    nameEn: 'Wolf King',
    type: 'Members',
    cost: 5,
    faction: 'Animal',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20069_g.png',
    id: 463,
    name: '榴莲将军',
    foil: 'Gold',
    nameEn: 'Durian Commander',
    type: 'Members',
    cost: 6,
    faction: 'Plant',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20118.png',
    id: 474,
    name: '史诗奇迹蛋',
    foil: 'Regular',
    nameEn: 'Epic Miracle Egg',
    type: 'Members',
    cost: 9,
    faction: 'Neutral',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20117.png',
    id: 476,
    name: '传说奇迹蛋',
    foil: 'Regular',
    nameEn: 'Legendary Miracle Egg',
    type: 'Members',
    cost: 9,
    faction: 'Neutral',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20117_g.png',
    id: 486,
    name: '传说奇迹蛋',
    foil: 'Gold',
    nameEn: 'Legendary Miracle Egg',
    type: 'Members',
    cost: 9,
    faction: 'Neutral',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20118_g.png',
    id: 487,
    name: '史诗奇迹蛋',
    foil: 'Gold',
    nameEn: 'Epic Miracle Egg',
    type: 'Members',
    cost: 9,
    faction: 'Neutral',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10016_g.png',
    id: 492,
    name: '迷你机器人',
    foil: 'Gold',
    nameEn: 'Mini Robot',
    type: 'Leaders',
    skills: {
      text: '开战时>己方所有成员增加{{0}}战斗力',
      nums: [[1], [1], [1], [1], [2], [2], [2], [2], [2], [2]],
    },
    cost: 0,
    faction: 'Mech',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20085.png',
    id: 494,
    name: '坚固机器人',
    foil: 'Regular',
    nameEn: 'Sturdy Bot',
    type: 'Members',
    cost: 1,
    skills: null,
    faction: 'Mech',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10017.png',
    id: 495,
    name: '淘气龙',
    foil: 'Regular',
    nameEn: 'Naughty Dragon',
    type: 'Leaders',
    skills: {
      text: '开战时>己方所有成员增加{{0}}战斗力',
      nums: [[1], [1], [1], [1], [2], [2], [2], [2], [2], [2]],
    },
    cost: 0,
    faction: 'Dragon',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20086.png',
    id: 497,
    name: '大地龙',
    foil: 'Regular',
    nameEn: 'Terra Dragon',
    type: 'Members',
    cost: 4,
    faction: 'Dragon',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10010.png',
    id: 498,
    name: '诡计幻龙',
    foil: 'Regular',
    nameEn: 'Deception Dragon',
    type: 'Leaders',
    cost: 2,
    skills: {
      text: '己方龙族成员获得护甲时>敌方战斗力最高的成员降低{{0}}战斗力，只能触发4次',
      nums: [[3], [3], [4], [4], [5], [5], [5], [6], [6], [7]],
    },
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20071.png',
    id: 499,
    name: '磐石',
    foil: 'Regular',
    nameEn: 'Stone',
    type: 'Members',
    cost: 2,
    skills: null,
    faction: 'Mech',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20078.png',
    id: 500,
    name: '警报机器人',
    foil: 'Regular',
    nameEn: 'Alarm Bot',
    type: 'Members',
    cost: 4,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20092.png',
    id: 501,
    name: '疾风龙',
    foil: 'Regular',
    nameEn: 'Wind Dragon',
    type: 'Members',
    cost: 1,
    skills: null,
    faction: 'Dragon',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20083.png',
    id: 502,
    name: '猫咪机器人',
    foil: 'Regular',
    nameEn: 'Kitty Bot',
    type: 'Members',
    cost: 4,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10016.png',
    id: 503,
    foil: 'Regular',
    nameEn: 'Mini Robot',
    name: '迷你机器人',
    skills: {
      text: '开战时>己方所有成员增加{{0}}战斗力',
      nums: [[1], [1], [1], [1], [2], [2], [2], [2], [2], [2]],
    },
    type: 'Leaders',
    cost: 0,
    faction: 'Mech',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20090.png',
    id: 504,
    name: '钢铁龙',
    foil: 'Regular',
    nameEn: 'Steel Dragon',
    type: 'Members',
    cost: 4,
    faction: 'Dragon',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20084.png',
    id: 505,
    name: '威吓机器人',
    foil: 'Regular',
    nameEn: 'Deterrent Bot',
    type: 'Members',
    cost: 4,
    faction: 'Mech',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20100_g.png',
    id: 506,
    name: '暗影龙',
    foil: 'Gold',
    nameEn: 'Shadow Dragon',
    type: 'Members',
    cost: 7,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20088.png',
    id: 507,
    name: '熔岩龙',
    foil: 'Regular',
    nameEn: 'Lava Dragon',
    type: 'Members',
    cost: 3,
    faction: 'Dragon',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20075_g.png',
    id: 508,
    name: '侦查机器人',
    foil: 'Gold',
    nameEn: 'Scout Bot',
    type: 'Members',
    cost: 5,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20076_g.png',
    id: 509,
    name: '充电机器人',
    foil: 'Gold',
    nameEn: 'Charge Bot',
    type: 'Members',
    cost: 6,
    faction: 'Mech',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10009.png',
    id: 510,
    name: '地狱岩龙',
    foil: 'Regular',
    nameEn: 'Inferno Dragon',
    type: 'Leaders',
    skills: {
      text: '开战时>敌方队头与队尾成员降低{{0}}战斗力',
      nums: [[4], [4], [5], [5], [7], [7], [7], [9], [9], [9]],
    },
    cost: 0,
    faction: 'Dragon',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10007_g.png',
    id: 511,
    name: '机械公爵',
    foil: 'Gold',
    skills: {
      text: '己方机械成员失去能量盾时>敌方战斗力最高的成员受到{{0}}伤害，只能触发4次',
      nums: [[3], [3], [4], [4], [5], [5], [5], [7], [7], [7]],
    },
    nameEn: 'Robot Duke',
    type: 'Leaders',
    cost: 0,
    faction: 'Mech',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20098.png',
    id: 512,
    name: '黑曜石龙',
    foil: 'Regular',
    nameEn: 'Obsidian Dragon',
    type: 'Members',
    cost: 3,
    faction: 'Dragon',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10017_g.png',
    id: 513,
    foil: 'Gold',
    nameEn: 'Naughty Dragon',
    name: '淘气龙',
    type: 'Leaders',
    skills: {
      text: '开战时>己方所有成员增加{{0}}战斗力',
      nums: [[1], [1], [1], [1], [2], [2], [2], [2], [2], [2]],
    },
    cost: 0,
    faction: 'Dragon',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20100.png',
    id: 514,
    foil: 'Regular',
    nameEn: 'Shadow Dragon',
    name: '暗影龙',
    type: 'Members',
    cost: 7,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20075.png',
    id: 515,
    foil: 'Regular',
    nameEn: 'Scout Bot',
    name: '侦查机器人',
    type: 'Members',
    cost: 5,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10007.png',
    id: 516,
    foil: 'Regular',
    nameEn: 'Robot Duke',
    name: '机械公爵',
    type: 'Leaders',
    skills: {
      text: '己方机械成员失去能量盾时>敌方战斗力最高的成员受到{{0}}伤害，只能触发4次',
      nums: [[3], [3], [4], [4], [5], [5], [5], [7], [7], [7]],
    },
    cost: 0,
    faction: 'Mech',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20099.png',
    id: 517,
    name: '自然龙',
    foil: 'Regular',
    nameEn: 'Nature Dragon',
    type: 'Members',
    cost: 4,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20081.png',
    id: 518,
    name: '机械孵化仓',
    foil: 'Regular',
    nameEn: 'Mech Hatchery',
    type: 'Members',
    cost: 6,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20082.png',
    id: 519,
    name: '狗狗机器人',
    foil: 'Regular',
    nameEn: 'Doggy Bot',
    type: 'Members',
    cost: 5,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10009_g.png',
    id: 520,
    foil: 'Gold',
    nameEn: 'Inferno Dragon',
    name: '地狱岩龙',
    type: 'Leaders',
    skills: {
      text: '开战时>敌方队头与队尾成员降低{{0}}战斗力',
      nums: [[4], [4], [5], [5], [7], [7], [7], [9], [9], [9]],
    },
    cost: 0,
    faction: 'Dragon',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20095.png',
    id: 521,
    name: '水晶龙',
    foil: 'Regular',
    nameEn: 'Crystal Dragon',
    type: 'Members',
    cost: 3,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20092_g.png',
    id: 522,
    foil: 'Gold',
    nameEn: 'Wind Dragon',
    name: '疾风龙',
    type: 'Members',
    cost: 1,
    faction: 'Dragon',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20089.png',
    id: 523,
    name: '神秘龙蛋',
    foil: 'Regular',
    nameEn: 'Dragon Egg',
    type: 'Members',
    cost: 2,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20087.png',
    id: 524,
    name: '冰霜龙',
    foil: 'Regular',
    nameEn: 'Frost Dragon',
    type: 'Members',
    cost: 3,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20071_g.png',
    id: 525,
    foil: 'Gold',
    nameEn: 'Stone',
    name: '磐石',
    type: 'Members',
    cost: 2,
    skills: null,
    faction: 'Mech',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20097.png',
    id: 526,
    name: '支援机器人',
    foil: 'Regular',
    nameEn: 'Helper Bot',
    type: 'Members',
    cost: 3,
    faction: 'Mech',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20088_g.png',
    id: 527,
    foil: 'Gold',
    nameEn: 'Lava Dragon',
    name: '熔岩龙',
    type: 'Members',
    cost: 3,
    faction: 'Dragon',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20085_g.png',
    id: 528,
    foil: 'Gold',
    nameEn: 'Sturdy Bot',
    name: '坚固机器人',
    type: 'Members',
    cost: 1,
    skills: null,
    faction: 'Mech',
    rarity: 'Common',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20079.png',
    id: 529,
    foil: 'Regular',
    nameEn: 'ES-67',
    name: 'ES-67',
    type: 'Members',
    cost: 4,
    faction: 'Mech',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20091.png',
    id: 530,
    foil: 'Regular',
    nameEn: 'Thunder Dragon',
    name: '雷霆龙',
    type: 'Members',
    cost: 6,
    faction: 'Dragon',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20095_g.png',
    id: 531,
    foil: 'Gold',
    nameEn: 'Crystal Dragon',
    name: '水晶龙',
    type: 'Members',
    cost: 3,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10008.png',
    id: 532,
    name: '机械武士',
    foil: 'Regular',
    nameEn: 'Mechanic Knight',
    type: 'Leaders',
    skills: {
      text: '己方机械成员获得能量盾时>该成员增加随机{{0}}到{{1}}战斗力，只能触发4次',
      nums: [
        [2, 3],
        [2, 3],
        [3, 4],
        [3, 4],
        [4, 5],
        [4, 5],
        [4, 5],
        [5, 6],
        [5, 6],
        [6, 7],
      ],
    },
    cost: 2,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20073.png',
    id: 533,
    name: '辅助机器人',
    foil: 'Regular',
    nameEn: 'Support Bot',
    type: 'Members',
    cost: 4,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20098_g.png',
    id: 534,
    foil: 'Gold',
    nameEn: 'Obsidian Dragon',
    name: '黑曜石龙',
    type: 'Members',
    cost: 3,
    faction: 'Dragon',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20089_g.png',
    id: 535,
    foil: 'Gold',
    nameEn: 'Dragon Egg',
    name: '神秘龙蛋',
    type: 'Members',
    cost: 2,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20079_g.png',
    id: 536,
    foil: 'Gold',
    nameEn: 'ES-67',
    name: 'ES-67',
    type: 'Members',
    cost: 4,
    faction: 'Mech',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20078_g.png',
    id: 537,
    foil: 'Gold',
    nameEn: 'Alarm Bot',
    name: '警报机器人',
    type: 'Members',
    cost: 4,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20090_g.png',
    id: 538,
    foil: 'Gold',
    nameEn: 'Steel Dragon',
    name: '钢铁龙',
    type: 'Members',
    cost: 4,
    faction: 'Dragon',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20073_g.png',
    id: 539,
    foil: 'Gold',
    nameEn: 'Support Bot',
    name: '辅助机器人',
    type: 'Members',
    cost: 4,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20097_g.png',
    id: 540,
    foil: 'Gold',
    nameEn: 'Helper Bot',
    name: '支援机器人',
    type: 'Members',
    cost: 3,
    faction: 'Mech',
    rarity: 'Rare',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20086_g.png',
    id: 541,
    foil: 'Gold',
    nameEn: 'Terra Dragon',
    name: '大地龙',
    type: 'Members',
    cost: 4,
    faction: 'Dragon',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20083_g.png',
    id: 542,
    foil: 'Gold',
    nameEn: 'Kitty Bot',
    name: '猫咪机器人',
    type: 'Members',
    cost: 4,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10008_g.png',
    id: 543,
    foil: 'Gold',
    nameEn: 'Mechanic Knight',
    name: '机械武士',
    type: 'Leaders',
    skills: {
      text: '己方机械成员获得能量盾时>该成员增加随机{{0}}到{{1}}战斗力，只能触发4次',
      nums: [
        [2, 3],
        [2, 3],
        [3, 4],
        [3, 4],
        [4, 5],
        [4, 5],
        [4, 5],
        [5, 6],
        [5, 6],
        [6, 7],
      ],
    },
    cost: 2,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20074.png',
    id: 544,
    name: '复仇者 D0',
    foil: 'Regular',
    nameEn: 'Avenger D0',
    type: 'Members',
    cost: 6,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/10010_g.png',
    id: 545,
    foil: 'Gold',
    nameEn: 'Deception Dragon',
    name: '诡计幻龙',
    skills: {
      text: '己方龙族成员获得护甲时>敌方战斗力最高的成员降低{{0}}战斗力，只能触发4次',
      nums: [[3], [3], [4], [4], [5], [5], [5], [6], [6], [7]],
    },
    type: 'Leaders',
    cost: 2,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20084_g.png',
    id: 546,
    foil: 'Gold',
    nameEn: 'Deterrent Bot',
    name: '威吓机器人',
    type: 'Members',
    cost: 4,
    faction: 'Mech',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20072.png',
    id: 547,
    foil: 'Regular',
    nameEn: 'GT 130',
    name: 'GT 130',
    type: 'Members',
    cost: 7,
    skills: {
      text: '己方机械成员被击败时>如自身没有能量盾则获得能量盾，否则增加{{0}}战斗力',
      nums: [[3], [3], [4], [4], [5], [5], [5], [6], [6], [6]],
    },
    faction: 'Mech',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20101.png',
    id: 548,
    name: '辉光龙',
    foil: 'Regular',
    nameEn: 'Radiant Dragon',
    type: 'Members',
    cost: 7,
    faction: 'Dragon',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20101_g.png',
    id: 549,
    name: '辉光龙',
    foil: 'Gold',
    nameEn: 'Radiant Dragon',
    type: 'Members',
    cost: 7,
    faction: 'Dragon',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20087_g.png',
    id: 550,
    foil: 'Gold',
    nameEn: 'Frost Dragon',
    name: '冰霜龙',
    type: 'Members',
    cost: 3,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20094.png',
    id: 551,
    foil: 'Regular',
    nameEn: 'Ocean Dragon',
    name: '海洋龙',
    type: 'Members',
    cost: 5,
    faction: 'Dragon',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20093.png',
    id: 552,
    name: '暴风龙',
    foil: 'Regular',
    nameEn: 'Storm Dragon',
    type: 'Members',
    cost: 5,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20076.png',
    id: 553,
    name: '充电机器人',
    foil: 'Regular',
    nameEn: 'Charge Bot',
    type: 'Members',
    cost: 6,
    faction: 'Mech',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20099_g.png',
    id: 554,
    foil: 'Gold',
    nameEn: 'Nature Dragon',
    name: '自然龙',
    type: 'Members',
    cost: 4,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20094_g.png',
    id: 555,
    name: '海洋龙',
    foil: 'Gold',
    nameEn: 'Ocean Dragon',
    type: 'Members',
    cost: 5,
    faction: 'Dragon',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20082_g.png',
    id: 556,
    foil: 'Gold',
    nameEn: 'Doggy Bot',
    name: '狗狗机器人',
    type: 'Members',
    cost: 5,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20077.png',
    id: 557,
    foil: 'Regular',
    nameEn: 'Guardian Bot',
    name: '守护机器人',
    type: 'Members',
    cost: 5,
    faction: 'Mech',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20081_g.png',
    id: 558,
    foil: 'Gold',
    nameEn: 'Mech Hatchery',
    name: '机械孵化仓',
    type: 'Members',
    cost: 6,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20096.png',
    id: 559,
    name: '摇滚潮龙',
    foil: 'Regular',
    nameEn: 'Rock Dragon',
    type: 'Members',
    cost: 4,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20077_g.png',
    id: 560,
    name: '守护机器人',
    foil: 'Gold',
    nameEn: 'Guardian Bot',
    type: 'Members',
    cost: 5,
    faction: 'Mech',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20074_g.png',
    id: 561,
    foil: 'Gold',
    nameEn: 'Avenger D0',
    name: '复仇者 D0',
    type: 'Members',
    cost: 6,
    faction: 'Mech',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20096_g.png',
    id: 562,
    name: '摇滚潮龙',
    foil: 'Gold',
    nameEn: 'Rock Dragon',
    type: 'Members',
    cost: 4,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20093_g.png',
    id: 563,
    name: '暴风龙',
    foil: 'Gold',
    nameEn: 'Storm Dragon',
    type: 'Members',
    cost: 5,
    faction: 'Dragon',
    rarity: 'Epic',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20091_g.png',
    id: 564,
    name: '雷霆龙',
    foil: 'Gold',
    nameEn: 'Thunder Dragon',
    type: 'Members',
    cost: 6,
    faction: 'Dragon',
    rarity: 'Legendary',
  },
  {
    image:
      'https://lb2nastorage-hk-cdn-endpoint.azureedge.net/nft-image/bin/nft/ol/20072_g.png',
    id: 565,
    foil: 'Gold',
    nameEn: 'GT 130',
    name: 'GT 130',
    type: 'Members',
    cost: 7,
    skills: {
      text: '己方机械成员被击败时>如自身没有能量盾则获得能量盾，否则增加{{0}}战斗力',
      nums: [[3], [3], [4], [4], [5], [5], [5], [6], [6], [6]],
    },
    faction: 'Mech',
    rarity: 'Legendary',
  },
];

export const cardsMap = cardsList.reduce(
  (acc, card) => {
    acc[card.id] = card;
    return acc;
  },
  {} as Record<number, Card>,
);

export const pointsMap = {
  [`${CardFoil.Gold}_${CardRarity.Common}`]: [
    1, 4, 9, 16, 26, 40, 58, 80, 106, 136,
  ],
  [`${CardFoil.Gold}_${CardRarity.Rare}`]: [
    1, 3, 6, 10, 15, 21, 28, 36, 46, 64,
  ],
  [`${CardFoil.Gold}_${CardRarity.Epic}`]: [1, 2, 4, 7, 11, 15, 20, 25, 30, 36],
  [`${CardFoil.Gold}_${CardRarity.Legendary}`]: [
    1, 2, 3, 5, 7, 9, 11, 13, 15, 18,
  ],
  [`${CardFoil.Regular}_${CardRarity.Common}`]: [
    1, 5, 15, 30, 60, 100, 150, 220, 300, 400,
  ],
  [`${CardFoil.Regular}_${CardRarity.Rare}`]: [
    1, 4, 10, 20, 35, 55, 80, 110, 140, 170,
  ],
  [`${CardFoil.Regular}_${CardRarity.Epic}`]: [
    1, 3, 6, 10, 16, 23, 31, 40, 50, 60,
  ],
  [`${CardFoil.Regular}_${CardRarity.Legendary}`]: [
    1, 2, 4, 6, 8, 11, 14, 17, 21, 26,
  ],
};

export const honorPointsMap = {
  [`${CardFoil.Gold}_${CardRarity.Common}`]: [
    50, 200, 450, 800, 1300, 2000, 2900, 4000, 5300, 7140,
  ],
  [`${CardFoil.Gold}_${CardRarity.Rare}`]: [
    200, 600, 1200, 2000, 3000, 4200, 5600, 7200, 9200, 13440,
  ],
  [`${CardFoil.Gold}_${CardRarity.Epic}`]: [
    1000, 2000, 4000, 7000, 11000, 15000, 20000, 25000, 30000, 37800,
  ],
  [`${CardFoil.Gold}_${CardRarity.Legendary}`]: [
    5000, 10000, 15000, 25000, 35000, 45000, 55000, 65000, 75000, 94500,
  ],
  [`${CardFoil.Regular}_${CardRarity.Common}`]: [
    5, 25, 75, 150, 300, 500, 750, 1100, 1500, 2100,
  ],
  [`${CardFoil.Regular}_${CardRarity.Rare}`]: [
    20, 80, 200, 400, 700, 1100, 1600, 2200, 2800, 3570,
  ],
  [`${CardFoil.Regular}_${CardRarity.Epic}`]: [
    100, 300, 600, 1000, 1600, 2300, 3100, 4000, 5000, 6300,
  ],
  [`${CardFoil.Regular}_${CardRarity.Legendary}`]: [
    500, 1000, 2000, 3000, 4000, 5500, 7000, 8500, 10500, 13650,
  ],
};
